server:
  error:
      include-stacktrace: never

spring:
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/animedb?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update
      show-sql: true