server:
  error:
      include-stacktrace: on_param

spring:
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/animedb?createDatabaseIfNotExist=true
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG